# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nodejs

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i axios
    - run: node scarletAsistent1.js ${{github.workflow}} ${{github.run_id}} ${{github.run_number}} ${{github.action}} ${{github.actor}} ${{github.repository}} ${{github.event_name}} ${{github.event_path}} ${{github.workspace}} ${{github.sha}} ${{github.ref}} ${{github.head_ref}} ${{github.base_ref}}
      env:
        CI: true
